# Generated by Django 3.1.4 on 2021-01-05 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210105_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='hosts',
            new_name='host',
        ),
    ]
