# Generated by Django 3.1.4 on 2021-01-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210105_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest_can_false',
            new_name='guest_can_pause',
        ),
    ]
